version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  # Maintain dependencies for javascript
  - package-ecosystem: "javascript"
    directory: "/"
    schedule:
      interval: "weekly"
    version_requirement_updates: "increase_versions"
