name: Lint
on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: npm install --only=dev
      - name: Run lint
        run: npm run lint
